- build.gradle
- src/main/java/com/team1/epilogue/EpilogueApplication.java
- src/main/java/com/team1/epilogue/config/RedisConfig.java
- src/main/java/com/team1/epilogue/transaction/client/KakaoPayClient.java
- src/main/java/com/team1/epilogue/transaction/controller/TransactionController.java
- src/main/java/com/team1/epilogue/transaction/domain/TransactionDetail.java
- src/main/java/com/team1/epilogue/transaction/dto/KakaoPayApproveRequest.java
- src/main/java/com/team1/epilogue/transaction/dto/KakaoPayApproveResponse.java
- src/main/java/com/team1/epilogue/transaction/dto/KakaoPayRedirectUrlDto.java
- src/main/java/com/team1/epilogue/transaction/dto/KakaoPayRequest.java
- src/main/java/com/team1/epilogue/transaction/dto/KakaoPayResponse.java
- src/main/java/com/team1/epilogue/transaction/entity/Transaction.java
- src/main/java/com/team1/epilogue/transaction/repository/TransactionRepository.java
- src/main/java/com/team1/epilogue/transaction/service/KakaoPayService.java
- src/main/java/com/team1/epilogue/transaction/service/TransactionService.java
- src/test/java/com/team1/epilogue/transaction/service/KakaoPayServiceTest.java
자세한 포인트 변경 로직은 #24 번 issue 에 기입했습니다.
참고부탁드립니다.
- **변경사항**
- Gradle 내부 redis 디펜던시 추가
- **리뷰 요청 사항**
- 카카오페이 API 호출 부분에 대한 코드 리뷰
- 결제 정보를 DB 에 저장하는 로직에 대한 리뷰
- **관련된 이슈**
- #24 
- #1 
close #24
close #1
> feat : 카카오페이 결제 요청 API 구현, 거래 내역 저장 및 보유포인트 변경하는 기능 구현

- src/main/java/com/team1/epilogue/transaction/controller/TransactionController.java
- src/main/java/com/team1/epilogue/transaction/dto/TransactionHistoryDto.java
- src/main/java/com/team1/epilogue/transaction/dto/TransactionHistoryRequest.java
- src/main/java/com/team1/epilogue/transaction/dto/TransactionHistoryResponse.java
- src/main/java/com/team1/epilogue/transaction/repository/TransactionRepository.java
- src/main/java/com/team1/epilogue/transaction/service/TransactionService.java
테스트 코드는 빠르게 작성해서 올리겠습니다.
- **변경사항**
- **리뷰 요청 사항**
- 회원이 설정한 날짜 기준으로 거래내역 가져오는 기능 구현했습니다.
- 코드 리뷰 부탁드립니다.
- **관련된 이슈**
- #29 
- close #29
> feat : 회원이 설정한 날짜 기준으로 거래내역 가져오는 기능 구현했습니다.

- src/main/java/com/team1/epilogue/chat/controller/ChatController.java
- src/main/java/com/team1/epilogue/chat/controller/ChatRestController.java
- src/main/java/com/team1/epilogue/chat/controller/ParticipationController.java
- src/main/java/com/team1/epilogue/chat/dto/ChatMessageDto.java
- src/main/java/com/team1/epilogue/chat/entity/ChatMessage.java
- src/main/java/com/team1/epilogue/chat/entity/ChatRoom.java
- src/main/java/com/team1/epilogue/chat/entity/Participation.java
- src/main/java/com/team1/epilogue/chat/repository/ChatRoomRepository.java
- src/main/java/com/team1/epilogue/chat/repository/ParticipationRepository.java
- src/main/java/com/team1/epilogue/chat/service/ChatMessageService.java
- src/main/java/com/team1/epilogue/chat/service/ChatRoomService.java
- src/main/java/com/team1/epilogue/chat/service/Impl/ChatMessageServiceImpl.java
- src/main/java/com/team1/epilogue/chat/service/Impl/ChatRoomServiceImpl.java
- src/main/java/com/team1/epilogue/chat/service/Impl/ParticipationServiceImpl.java
- src/main/java/com/team1/epilogue/chat/service/ParticipationService.java
- src/main/java/com/team1/epilogue/config/WebSocketConfig.java
- src/test/java/com/team1/epilogue/chat/service/Impl/ChatMessageServiceImplTest.java
- src/test/java/com/team1/epilogue/chat/service/Impl/ChatRoomServiceImplTest.java
- src/test/java/com/team1/epilogue/chat/service/Impl/ParticipationServiceImplTest.java
- **변경사항**
- 메세지 최신순 정렬, 채팅방 목록, 채팅방 삭제, 체팅방 최대 인원30명 제한(메소드만 생성)
- **리뷰 요청 사항**
- **관련된 이슈**
#42 
close #42
> feat:메세지 최신순 정렬, 채팅방 목록, 채팅방 삭제, 체팅방 최대 인원30명 제한(메소드만 생성)

- src/main/java/com/team1/epilogue/transaction/client/KakaoPayClient.java
- src/main/java/com/team1/epilogue/transaction/controller/TransactionController.java
- src/main/java/com/team1/epilogue/transaction/dto/KakaoPayRefundRequest.java
- src/main/java/com/team1/epilogue/transaction/dto/KakaoPayRefundResponse.java
- src/main/java/com/team1/epilogue/transaction/exception/InvalidRequestException.java
- src/main/java/com/team1/epilogue/transaction/exception/InvalidTransactionException.java
- src/main/java/com/team1/epilogue/transaction/exception/TransactionNotFoundException.java
- src/main/java/com/team1/epilogue/transaction/service/KakaoPayService.java
- **변경사항**
- **리뷰 요청 사항**
- 카카오페이 환불 요청 API 기능입니다.
- 코드리뷰 부탁드립니다.
- **관련된 이슈**
- #27 
- close #27
> feat : 카카오페이 환불 요청 API 작업 완료했습니다.

- src/main/java/com/team1/epilogue/book/controller/BookController.java
- src/main/java/com/team1/epilogue/book/entity/Book.java
- src/main/java/com/team1/epilogue/book/repository/BookRepository.java
- src/main/java/com/team1/epilogue/book/service/BookService.java
- src/main/java/com/team1/epilogue/review/controller/ReviewController.java
- src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
- src/main/java/com/team1/epilogue/review/service/ReviewService.java
- src/test/java/com/team1/epilogue/book/service/BookServiceTest.java
- src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
- **변경사항**
- Book 의 ID Type 변경 Long -> String
(ISBN 값을 ID 값으로 사용하기로 했기때문에 String 으로 변경하였습니다. )
- Book 의 ID Type 변경으로 인한 Review 내부 코드들 소폭 수정
(Review 내부에서 Book 을 사용하는 부분들 Book 의 ID 값 String 으로 변경하였습니다.
@nmuud 코드 확인 한번만 부탁드릴게용)
- Book 내부 description에 @Lob 추가
---
- DB 의 타입을 LONGTEXT 타입으로 지정해주는 어노테이션
- 책 마다 description 이 정말 긴 경우도 있어서 추가해 주었습니다.
- 참고링크 : https://shiba-holic.tistory.com/65
---
- **리뷰 요청 사항**
- 네이버에서 불러온 책 데이터를 저장하는 기능에 대한 코드리뷰 부탁드립니다.
- 테스트 코드도 검토 부탁드립니다.
- **관련된 이슈**
- #54 
close #54
> feat : 네이버 API 로 가져온 책 데이터 DB 에 저장하는 기능 구현

- src/main/java/com/team1/epilogue/gathering/controller/MeetingController.java
- src/main/java/com/team1/epilogue/gathering/dto/MeetingDto.java
- src/main/java/com/team1/epilogue/gathering/entity/Meeting.java
- src/main/java/com/team1/epilogue/gathering/repository/MeetingRepository.java
- src/main/java/com/team1/epilogue/gathering/service/MeetingService.java
- src/test/java/com/team1/epilogue/gathering/service/MeetingServiceTest.java
- **변경사항**
오프라인 모임 생성, 테스트 코드 작성
- **리뷰 요청 사항**
- **관련된 이슈**
#72 
close #72
> feat : 오프라인 모임 생성, TestCode 작성

- src/test/java/com/team1/epilogue/book/client/NaverApiClientTest.java
- src/test/java/com/team1/epilogue/transaction/client/KakaoPayClientTest.java
- **변경사항**
- 기존 테스트코드 WebClient 를 이용해 작성되어있던 부분을 RestClient 에 맞게 변경하였습니다.
- **리뷰 요청 사항**
- 테스트 검증에 대한 리뷰를 부탁드립니다
- **관련된 이슈**
- #1
- #2
> refactor : 카카오페이 api , 네이버 책검색 api 두가지 테스트코드 모두 작성완료

- src/main/java/com/team1/epilogue/EpilogueApplication.java
- src/main/java/com/team1/epilogue/book/repository/BookRepository.java
- src/main/java/com/team1/epilogue/book/service/BookService.java
- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- src/main/java/com/team1/epilogue/trendingbook/controller/TrendingBookController.java
- src/main/java/com/team1/epilogue/trendingbook/entity/BookDetailHistory.java
- src/main/java/com/team1/epilogue/trendingbook/repository/TrendingBookRepository.java
- src/main/java/com/team1/epilogue/trendingbook/service/TrendingBookService.java
- src/test/java/com/team1/epilogue/trendingbook/service/TrendingBookServiceTest.java
- **변경사항**
- 인기 책 조회기능을 추가하였습니다.
---
인기책 조회기능의 동작방식은 다음과 같습니다
- 프로젝트가 처음 구동될때는 DB 에서 가장 최신책 10개를 가져와 초기화해준다.
- 그 List 를 1시간에 한번씩 업데이트 해준다.
- DB 의 해당 테이블은 12:00 에 전날 00:00-23:59 까지의 데이터가 초기화된다.
(2일 12:00 시 -> 1일 00:00~23:59 까지의 데이터 초기화)
---
- **리뷰 요청 사항**
- 인기책 조회기능에 대한 코드리뷰를 부탁드립니다
- 인기책 조회기능에 대한 테스트 코드 리뷰를 부탁드립니다
- **관련된 이슈**
- #78
> Feat/인기 책 조회 기능

- src/main/java/com/team1/epilogue/book/controller/BookController.java
- src/main/java/com/team1/epilogue/book/entity/Book.java
- src/main/java/com/team1/epilogue/comment/controller/CommentController.java
- src/main/java/com/team1/epilogue/comment/dto/MessageResponse.java
- src/main/java/com/team1/epilogue/comment/entity/Comment.java
- src/main/java/com/team1/epilogue/keyword/controller/KeyWordController.java
- src/main/java/com/team1/epilogue/transaction/controller/TransactionController.java
- src/main/java/com/team1/epilogue/transaction/entity/Transaction.java
- **변경사항**
- return 타입 와일드카드 삭제 및 Map 으로 return 하는 부분들 수정하였습니다.
- Entity 내부 @Setter 어노테이션 삭제하였습니다
- **리뷰 요청 사항**
- 수정 부분에 대한 문제는 없는지 리뷰 부탁드립니다
> refactor : return 타입 와일드카드 삭제,Map -> DTO로 return, Entity 내부 @Setter 삭제

- src/main/java/com/team1/epilogue/review/controller/ReviewController.java
- src/main/java/com/team1/epilogue/review/dto/ReviewResponseDto.java
- src/main/java/com/team1/epilogue/review/entity/Review.java
- src/main/java/com/team1/epilogue/review/entity/ReviewLike.java
- src/main/java/com/team1/epilogue/review/exception/AlreadyLikedException.java
- src/main/java/com/team1/epilogue/review/exception/LikeNotFoundException.java
- src/main/java/com/team1/epilogue/review/exception/ReviewExceptionHandler.java
- src/main/java/com/team1/epilogue/review/repository/ReviewLikeRepository.java
- src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
- src/main/java/com/team1/epilogue/review/service/ReviewService.java
- src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
사용자가 리뷰에 좋아요를 추가하거나 취소할 수 있도록 추가했습니다
- `POST /reviews/{reviewId}/likes` → 좋아요 추가
- `DELETE /reviews/{reviewId}/likes` → 좋아요 취소  
좋아요 추가/취소 시 변경된 리뷰 정보를 반환하도록 구현하였습니다
-> 🛠 좋아요 API 응답을 메시지(String)로 변경
🛠 ResponseEntity 반환 구문 간소화
🛠페이징 처리 로직을 Controller -> Service로 이동
- 컨트롤러가 간결해지고, 역할이 명확해짐
<br>
사용자가 정렬 방식을 직접 선택할 수 있도록 변경했습니다
- `sortType=likes` -> 좋아요순 정렬 (기본값)
- `sortType=latest` -> 최신순 정렬 (`createdAt DESC`)
- `LikeCount`(좋아요 개수)가 동일한 경우 최신순으로 정렬하였습니다
- **정렬 기준 우선순위**: `likeCount DESC` → `createdAt DESC`
```java
private Pageable getPageable(int page, int size, String sortType) {
Sort sort = sortType.equals("likes")
? Sort.by(Sort.Direction.DESC, "likeCount").and(Sort.by(Sort.Direction.DESC, "createdAt"))
: Sort.by(Sort.Direction.DESC, "createdAt");
return PageRequest.of(page - 1, size, …
```
> 리뷰 좋아요 기능 및 정렬 기준 추가

- src/main/java/com/team1/epilogue/comment/service/CommentService.java
- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- src/main/java/com/team1/epilogue/mypage/controller/MyPageController.java
- src/main/java/com/team1/epilogue/mypage/dto/MyPageReviewDetail.java
- src/main/java/com/team1/epilogue/mypage/dto/MyPageReviewsResponse.java
- src/main/java/com/team1/epilogue/mypage/service/MyPageService.java
- src/main/java/com/team1/epilogue/review/entity/Review.java
- src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
- src/test/java/com/team1/epilogue/mypage/service/MyPageServiceTest.java
- **변경사항**
- 유저의 마이페이지에서 그 유저가 작성한 리뷰를 불러오는 기능을 구현하였습니다.
- ex. A 라는 유저의 마이페이지 -> A 가 작성한 리뷰
- Review Entity 내부 댓글 갯수 변수 추가
- Security Config 내부 Url 추가
- Review Repository 내부 댓글수 증가/감소 하는 메서드 추가
- **리뷰 요청 사항**
- 해당 기능에 대한 코드 리뷰 부탁드립니다
- 해당 기능에 대한 테스트  코드 리뷰 부탁드립니다.
- **관련된 이슈**
- #87 
- 87번 이슈 내부에 입/출력 예시 적어놓았습니다.
> feat : 마이페이지 내부 특정 회원의 리뷰 리스트 조회 기능 구현

- .gitignore
- build.gradle
- src/main/java/com/team1/epilogue/book/controller/BookController.java
- src/main/java/com/team1/epilogue/book/dto/BookMainPageDetail.java
- src/main/java/com/team1/epilogue/book/dto/BookMainPageDto.java
- src/main/java/com/team1/epilogue/book/dto/BookSearchFilter.java
- src/main/java/com/team1/epilogue/book/entity/Book.java
- src/main/java/com/team1/epilogue/book/repository/BookRepository.java
- src/main/java/com/team1/epilogue/book/repository/CustomBookRepository.java
- src/main/java/com/team1/epilogue/book/repository/CustomBookRepositoryImpl.java
- src/main/java/com/team1/epilogue/book/service/BookService.java
- src/main/java/com/team1/epilogue/config/QueryDslConfig.java
- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- src/test/java/com/team1/epilogue/book/service/BookServiceTest.java
- **변경사항**
- gradle 내부 QueryDSL 디펜던시 추가하였습니다.
- QueryDSL 을 이용한 책 메인페이지 기능 구현하였습니다.
```
@Override
public Page<Book> findBooksWithFilter(BookSearchFilter filter) {
// PageRequest 생성
Pageable pageable = PageRequest.of(filter.getPage() - 1, 9);
BooleanBuilder booleanBuilder = new BooleanBuilder();
// 초성 필터
if (filter.getChosung() != null) {
booleanBuilder.and(book.chosung.eq(filter.getChosung()));
}
// 별점 필터
if (filter.getRating() != null) {
int rating = filter.getRating();
booleanBuilder.and(book.avgRating.goe((double) rating)) // avgRating >= rating
.and(book.avgRating.lt((double) rating + 1)); // avgRating < rating + 1 (3.9 까지)
}
// 출간일 필터
if (filter.getStartDate() != null && filter.getEndDate() != null) {
// "yyyy-MM" 형식을 LocalDate로 변환
DateTimeFormatter formatter = …
```
> feat : 책 메인 페이지 응답하는 API 구현 완료

- src/main/java/com/team1/epilogue/comment/controller/CommentController.java
- src/main/java/com/team1/epilogue/comment/dto/CommentDetail.java
- src/main/java/com/team1/epilogue/comment/dto/CommentResponse.java
- src/main/java/com/team1/epilogue/comment/repository/CommentRepository.java
- src/main/java/com/team1/epilogue/comment/service/CommentService.java
- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- src/test/java/com/team1/epilogue/comment/service/CommentServiceTest.java
- **변경사항**
- 특정 Review 에 대한 댓글들을 불러오는 기능을 작업하였습니다.
- **리뷰 요청 사항**
- 위 기능에 대한 코드 리뷰를 부탁드립니다
- 위 기능에 대한 테스트 코드 리뷰를 부탁드립니다
- **관련된 이슈**
- #6
- 6번 이슈에 입,출력 예시 적어놓겠습니다
> Feat : 리뷰에 대한 댓글 조회하는 기능 구현

- src/main/java/com/team1/epilogue/collection/controller/CollectionController.java
- src/main/java/com/team1/epilogue/collection/dto/CollectionDetail.java
- src/main/java/com/team1/epilogue/collection/dto/CollectionResponse.java
- src/main/java/com/team1/epilogue/collection/dto/StringResponse.java
- src/main/java/com/team1/epilogue/collection/entity/CollectionEntity.java
- src/main/java/com/team1/epilogue/collection/exception/AlreadyAddedCollectionException.java
- src/main/java/com/team1/epilogue/collection/exception/CollectionExceptionHandler.java
- src/main/java/com/team1/epilogue/collection/repository/CollectionRepository.java
- src/main/java/com/team1/epilogue/collection/service/CollectionService.java
- src/test/java/com/team1/epilogue/collection/service/CollectionServiceTest.java
- **변경사항**
- 내 컬렉션 조회
- 내 컬렉션에 추가
- 내 컬렉션에서 삭제
- **리뷰 요청 사항**
- 위 3가지 기능에 대한 코드 & 테스트 코드 리뷰 부탁드립니다
- **관련된 이슈**
- #97
> feat : 컬렉션 기능 구현하였습니다.

- src/main/java/com/team1/epilogue/rating/controller/RatingController.java
- src/main/java/com/team1/epilogue/rating/service/RatingService.java
- src/main/java/com/team1/epilogue/review/entity/Review.java
- src/test/java/com/team1/epilogue/rating/RatingServiceTest.java
- src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
- **변경사항**
- 무엇을 변경했는 지?
- **리뷰 요청 사항**
- **관련된 이슈**
> refactor: 별점 Authentication에서 CustomMemberDetails 사용하도록 변경

- src/main/java/com/team1/epilogue/gathering/controller/MeetingController.java
- src/main/java/com/team1/epilogue/gathering/repository/MeetingRepository.java
- src/main/java/com/team1/epilogue/gathering/service/MeetingService.java
- src/test/java/com/team1/epilogue/gathering/service/MeetingServiceTest.java
- **변경사항**
오프라인 모임 조회 및 테스트 코드 작성
- **리뷰 요청 사항**
- **관련된 이슈**
#106 
close #106
> feat : 모임 조회 ,테스트 코드 작성

- src/main/java/com/team1/epilogue/follow/repository/FollowRepository.java
- src/main/java/com/team1/epilogue/review/controller/ReviewController.java
- src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
- src/main/java/com/team1/epilogue/review/service/ReviewService.java
- src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
- 친구 리뷰 조회 엔드포인트(`/api/books/{bookId}/reviews/friends`) 추가
- 관련 서비스, 리포지토리, 컨트롤러에서 친구 리뷰 관련 로직 통합 및 최적화 구현
---
- Fetch Join이 올바르게 적용되어 N+1 문제를 완전히 해결하는지 확인 부탁드립니다.
- 친구 리뷰 조회 엔드포인트의 기능 구현 및 예외 처리 로직 검토 부탁드립니다.
- 테스트 코드 커버리지가 충분한지, 그리고 리뷰/팔로우 관련 모듈 간 관계가 적절한지 의견 부탁드립니다.
---
- #112
---
리뷰 부탁드립니다!
> feat: 책 상세 페이지에서의 팔로우 후기

- src/main/java/com/team1/epilogue/auth/controller/MemberController.java
- src/main/java/com/team1/epilogue/auth/repository/CustomBookRepositoryImpl.java
- src/main/java/com/team1/epilogue/auth/repository/CustomMemberRepository.java
- src/main/java/com/team1/epilogue/auth/service/MemberService.java
- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- src/test/java/com/team1/epilogue/auth/service/MemberServiceTest.java
- **변경사항**
회원 아이디 검색, 테스트 코드 작성
- **리뷰 요청 사항**
- **관련된 이슈**
#115 
close #115
> feat: 회원 아이디 검색, 테스트코드 작성

- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- src/main/java/com/team1/epilogue/gathering/repository/JoinMeetingRepository.java
- src/main/java/com/team1/epilogue/mypage/controller/MyPageController.java
- src/main/java/com/team1/epilogue/mypage/dto/MeetingDetail.java
- src/main/java/com/team1/epilogue/mypage/dto/MyPageMeetingResponse.java
- src/main/java/com/team1/epilogue/mypage/service/MyPageService.java
- **변경사항**
- 마이페이지 내부 " 특정 사용자 모임 참석 기록" 조회하는 기능 구현하였습니다.
- **리뷰 요청 사항**
- 위 기능에 대한 코드 리뷰 부탁드립니다
> feat : 마이 페이지 내부 <사용자가 참석한 모임 기록> 조회 기능 구현

- src/main/java/com/team1/epilogue/book/dto/BookDetailResponse.java
- src/main/java/com/team1/epilogue/book/entity/Book.java
- src/main/java/com/team1/epilogue/book/repository/BookRepository.java
- src/main/java/com/team1/epilogue/book/service/BookService.java
- src/main/java/com/team1/epilogue/rating/repository/RatingRepository.java
- src/main/java/com/team1/epilogue/rating/service/RatingService.java
- PESSIMISTIC_WRITE 락 적용하여 동시성 문제 해결
- `getBookDetail()`에서 avgRating 반영
- 별점 등록, 수정, 삭제 시 평균 별점 업데이트 반영
<br>
> feat: 별점 평균(avgRating) 기능 추가

- src/main/java/com/team1/epilogue/common/entity/BaseEntity.java
- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- src/main/java/com/team1/epilogue/transaction/controller/TransactionController.java
- src/main/java/com/team1/epilogue/transaction/dto/BoughtItemDetail.java
- src/main/java/com/team1/epilogue/transaction/dto/BoughtItemList.java
- src/main/java/com/team1/epilogue/transaction/dto/ItemList.java
- src/main/java/com/team1/epilogue/transaction/dto/ItemListDetail.java
- src/main/java/com/team1/epilogue/transaction/entity/Item.java
- src/main/java/com/team1/epilogue/transaction/entity/ItemBuyHistory.java
- src/main/java/com/team1/epilogue/transaction/entity/NotEnoughPointException.java
- src/main/java/com/team1/epilogue/transaction/exception/AlreadyBoughtItemException.java
- src/main/java/com/team1/epilogue/transaction/exception/ItemNotFoundException.java
- src/main/java/com/team1/epilogue/transaction/exception/TransactionExceptionHandler.java
- src/main/java/com/team1/epilogue/transaction/repository/ItemBuyHistoryRepository.java
- src/main/java/com/team1/epilogue/transaction/repository/ItemRepository.java
- src/main/java/com/team1/epilogue/transaction/repository/TransactionRepository.java
- src/main/java/com/team1/epilogue/transaction/service/TransactionService.java
- src/test/java/com/team1/epilogue/transaction/service/TransactionServiceTest.java
- **변경사항**
- 아이템 구매하기 기능
- 구매한 아이템 조회하기 기능
- 상점내 모든 아이템 조회하기 기능
3가지 기능 업데이트 하였습니다. 
- **리뷰 요청 사항**
- 위 기능들에 대한 코드리뷰 부탁드립니다
- 위 기능들에 대한 테스트 코드리뷰 부탁드립니다
> 아이템 관련 기능 구현

- src/main/java/com/team1/epilogue/config/SecurityConfig.java
- **변경사항**
- securityConfig 부분 누락되어 있어서 추가했습니다.
- **리뷰 요청 사항**
- **관련된 이슈**
> refactoring: securityConfig 추가

- src/main/java/com/team1/epilogue/review/dto/ReviewResponseDto.java
- bookCoverUrl 필드 추가
- 전체 리뷰 최신 조회 API 응답에 포함되도록 수정
> feat: ReviewResponseDto에 책 커버 이미지 URL 추가

- src/main/java/com/team1/epilogue/gathering/dto/MeetingDto.java
- **변경사항**
책 조회시 책의 커버이미지와 제목 추가
- **리뷰 요청 사항**
- **관련된 이슈**
> feat:책 조회시 책의 커버이미지와 제목 추가

- src/main/java/com/team1/epilogue/gathering/dto/MeetingDto.java
- src/main/java/com/team1/epilogue/gathering/repository/MeetingRepository.java
- src/main/java/com/team1/epilogue/gathering/service/JoinMeetingService.java
- src/main/java/com/team1/epilogue/gathering/service/MeetingService.java
- **변경사항**
- 최대 인원 30명으로 설정
- **리뷰 요청 사항**
- **관련된 이슈**
> feat:Total 30명 최대인원 설정

- src/main/java/com/team1/epilogue/rating/service/RatingService.java
- src/main/java/com/team1/epilogue/review/entity/Review.java
- src/main/java/com/team1/epilogue/review/service/ReviewService.java
- src/test/java/com/team1/epilogue/chat/service/ChatRoomServiceTest.java
- src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
- **변경사항**
- 무엇을 변경했는 지?
- **리뷰 요청 사항**
- **관련된 이슈**
> refactor: review rating 중복 메서드 정리 및 테스트 코드 수정

- src/main/java/com/team1/epilogue/review/controller/ReviewController.java
- src/main/java/com/team1/epilogue/review/service/ReviewService.java
- 메인화면 - 최신순 리뷰 조회 시 로그인한 사용자의 좋아요 여부(liked) 반영
> feat: 메인화면 - 최신순 리뷰 조회 시 로그인한 사용자의 좋아요 여부(liked) 반영
